### PR TITLE
Avoid 302 redirects for Image List

### LINKED ISSUE #218: Image src in Image List component cause 302 redirect
### Expected Behaviour
Image src attribute should be set to the proper location of the images, so that the image can be cached longer.

### Actual Behaviour

Images within the Image List component are prompting a 302 redirect. This causes an unnecessary round trip and hurts the caching strategy.

image

This is most likely due to the implementation of creating a synthetic resource with the image...

#### Steps to Reproduce

1. Navigate to https://wknd.site/us/en.html
2. Observe that images loaded in ImageList component have a 302 redirect and cause a cache miss.

### PR DESCRIPTION
**Pull request by godanny86**
## Description

Wraps all of the original properties of the referenced image. This includes the timestamp which will make sure that caching/updates to the underlying image behave as expected.

## Related Issue

Fixes #218 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](https://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

File: core/src/test/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImplTest.java [hunk 1]
```diff
@@ -156,12 +156,13 @@ void SimpleImageComponentResource_getValueMap() {
 
         final ValueMap actual = new ImageListImpl.SimpleImageComponentResource(imageResource, "Test alt text").getValueMap();
 
-        assertEquals(5, actual.values().size());
+        assertEquals(8, actual.values().size());
         assertEquals("/content/dam/test.png", actual.get("fileReference"));
```
Comment (davidjgonzalez) [inline core/src/test/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImplTest.java:160]: Maybe add the test criteria to make sure that the expected lastmodified property value (and/or whatever else impacts the hash) are infact proxied through since that is the underlying fix here?

File: core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImpl.java [hunk 2]
```diff
@@ -280,15 +280,15 @@ public String getId() {
...
-            properties.put(PN_FILE_REFERENCE,
-                    resource.getValueMap().get(PN_FILE_REFERENCE));
+            // Copy the properties from the original image
+            properties.putAll(resource.getValueMap());
 
             // Override the decorative configuration attributes
             properties.put(PN_ALT, alt);
             properties.put(Image.PN_IS_DECORATIVE, false);
-            properties.put(Image.PN_DISPLAY_POPUP_TITLE, false);
+            properties.put(Image.PN_DISPLAY_POPUP_TITLE, true);
```
Comment (davidjgonzalez) [inline core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImpl.java:289]: Is this being written out as HTML now just to be hidden via CSS?  Don't recall the BEM's off the top of my head to match these up.

```
.cmp-image__title {
      display: none;
  }
```

Comment (godanny86) [reply core/src/main/java/com/adobe/aem/guides/wknd/core/models/impl/ImageListImpl.java:289]: less is more :)
